module.exports = Object.freeze({
  TITLE_START1: 'instruction title is',
  TITLE_END1: 'tools',
  TITLE_END2: 'safety',
  TITLE_END3: 'spare parts',
  TITLE_END4: 'step one',
  TITLE_END5: 'step 1',
  TITLE_END6: 'step',
  TITLE_END7: '',
  TITLE_START_POSSIBILITIES: 1,
  TITLE_END_POSSIBILITIES: 7,
  STEP_MESSAGE_START1: 'step ${digit} title is',
  STEP_MESSAGE_START2: 'step ${word} title is',
  STEP_MESSAGE_START3: 'step ${digit}',
  STEP_MESSAGE_START4: 'step ${word}',
  STEP_MESSAGE_END1: 'step ${digit}',
  STEP_MESSAGE_END2: 'step ${word}',
  STEP_MESSAGE_END3: 'step',
  STEP_MESSAGE_END4: '',
  STEP_MESSAGE_START_POSSIBILITIES: 4,
  STEP_MESSAGE_END_POSSIBILITIES: 4,
  STEP_TITLE_START1: 'step ${digit} title is',
  STEP_TITLE_START2: 'step ${word} title is',
  STEP_TITLE_START3: 'step ${digit}',
  STEP_TITLE_START4: 'step ${word}',
  STEP_TITLE_END1: 'instruction',
  STEP_TITLE_END2: 'warning',
  STEP_TITLE_END3: 'hint',
  STEP_TITLE_END4: 'reaction plan',
  STEP_TITLE_END5: 'step',
  STEP_TITLE_END6: '',
  STEP_TITLE_START_POSSIBILITIES: 4,
  STEP_TITLE_END_POSSIBILITIES: 6,
  STEP_INS_START1: 'instruction',
  STEP_INS_END1: 'warning',
  STEP_INS_END2: 'hint',
  STEP_INS_END3: 'reaction plan',
  STEP_INS_END4: 'step ${digit}',
  STEP_INS_END5: 'step ${word}',
  STEP_INS_END6: 'step',
  STEP_INS_END7: '',
  STEP_INS_START_POSSIBILITIES: 1,
  STEP_INS_END_POSSIBILITIES: 7,
  STEP_WARN_START1: 'warning',
  STEP_WARN_END1: 'instruction',
  STEP_WARN_END2: 'hint',
  STEP_WARN_END3: 'reaction plan',
  STEP_WARN_END4: 'step ${digit}',
  STEP_WARN_END5: 'step ${word}',
  STEP_WARN_END6: 'step',
  STEP_WARN_END7: '',
  STEP_WARN_START_POSSIBILITIES: 1,
  STEP_WARN_END_POSSIBILITIES: 7,
  STEP_HINT_START1: 'hint',
  STEP_HINT_END1: 'instruction',
  STEP_HINT_END2: 'warning',
  STEP_HINT_END3: 'reaction plan',
  STEP_HINT_END4: 'step ${digit}',
  STEP_HINT_END5: 'step ${word}',
  STEP_HINT_END6: 'step',
  STEP_HINT_END7: '',
  STEP_HINT_START_POSSIBILITIES: 1,
  STEP_HINT_END_POSSIBILITIES: 7,
  STEP_RPLAN_START1: 'reaction plan',
  STEP_RPLAN_END1: 'instruction',
  STEP_RPLAN_END2: 'warning',
  STEP_RPLAN_END3: 'hint',
  STEP_RPLAN_END4: 'step ${digit}',
  STEP_RPLAN_END5: 'step ${word}',
  STEP_RPLAN_END6: 'step',
  STEP_RPLAN_END7: '',
  STEP_RPLAN_START_POSSIBILITIES: 1,
  STEP_RPLAN_END_POSSIBILITIES: 7,
  NUMBERS: ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve',
  'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty', 'twenty one',
'twenty two', 'twenty three', 'twenty four', 'twenty five', 'twenty six', 'twenty seven', 'twenty eight', 'twenty nine', 'thirty', 'thirty one'],
  SCREEN_SHOT_WORD1: 'much',
  SCREEN_SHOT_WORD2: 'better'
})
