image: ubuntu:cwpnode
stages:
  - build
  - test

build-job:
  stage: build
  tags:
    - cwpunittests

  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - sudo npm install
  only:
    - CWP-CodeBase

test-job1:
  stage: test
  tags:
    - cwpunittests
  script:
    - echo "This job tests something"
    - sudo npm run test-headless
  only:
    - CWP-CodeBase
  
