--- 
sonar_scan: 
  only: 
    - merge_requests
    - CWP-CodeBase
    - master
  script: 
    - "/opt/sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=CWP_FrontEnd -Dsonar.sources=src/app -Dsonar.test=src/app -Dsonar.login=c9bd7998c6f6313391a57c41031fae20d5b5c070 -Dsonar.projectVersion=$CI_COMMIT_SHORT_SHA -Dsonar.qualitygate.wait=true"
  stage: sonar
  tags: 
    - build
stages: 
  - sonar
