image: node:latest
#image: ubuntu:latest
variables:
  GIT_DEPTH: 10
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME
cache:
  key: ${CI_PROJECT_ID}

stages:
  - stage_build
  - stage_test

build:
  stage: stage_build
  script:
    - ls la
    - npm update
  tags:
    - build
  only:
    - CWP-CodeBase


test:
  stage: stage_test
  script:
    - npm run test-headless
  tags:
    - build
  only:
    - CWP-CodeBase
