#############3
variables:
  - GIT_SSL_NO_VERIFY: true
stages:
  - build
  - test
build-code-job:
  stage: build
  script:
    - echo “valid successful”
test-code-job1:
  stage: test
  script:
    - echo “test successful”
