--- 
cache: 
  paths: 
    - node_modules/
image: "node:latest"
install_dependencies: 
  artifacts: 
    paths: 
      - node_modules/
  script: 
    - "npm install"
  stage: build
stages: 
  - build
  - test
tags: "-test"
testing_testing: 
  script: "npm run test-headless"
  stage: test


