#image: node:latest
stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - npm install
  only:
    - CWP-CodeBase

test-job1:
  stage: test
  script:
    - echo "This job tests something"
    - npm run test-headless
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
  only:
    - CWP-CodeBase
