#image: node:latest
#image: ubuntu:latest
stages:
  - build
  - test
#variables:
 # GIT_DEPTH: 10
 # GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME
#cache:
 # key: ${CI_PROJECT_ID}

build_job:
  stage: build
  script:
    - ls la
    - npm install
  tags:
    - build
  only:
    - CWP-CodeBase


test_job:
  stage: test
  script:
    - npm run test-headless
  tags:
    - test
  only:
    - CWP-CodeBase
