 stages:
   - sonar

sonar_scan:
#  allow_failure: true
  only:
    - merge_requests
    - CWP-CodeBase
	  - master
  stage: sonar
  script:
     - /usr/local/bin/sonar-scanner -Dsonar.projectKey=CWP_FrontEnd -Dsonar.sources=. -Dsonar.login=c9bd7998c6f6313391a57c41031fae20d5b5c070 -Dsonar.projectVersion=$CI_COMMIT_SHORT_SHA -Dsonar.qualitygate.wait=true
  tags:
    - build
