stages:
  - test
cache:
  paths:
  - node_modules/

test-job1:
  stage: test
  image: ubuntu:cwpnode
  tags:
    - cwpunittests
  script:
    - echo "This job tests something"
	- sudo npm install
    - sudo npm run test-headless
  only:
    - CWP-CodeBase
