--- 
sonar_scan: 
  only: 
    - merge_requests
    - CWP-CodeBase
    - master
  script: 
    - "/opt/sonar-scanner -Dsonar.projectKey=CWP_FrontEnd -Dsonar.sources=. -Dsonar.login=0c944d624eb7cd91be1032c2fba283635305c36b -Dsonar.projectVersion=$CI_COMMIT_SHORT_SHA -Dsonar.qualitygate.wait=true"
  stage: sonar
  tags: 
    - build
stages: 
  - sonar

