--- 
image: "node:latest"
stages: 
  - build
  - test
cache: 
  paths: 
    - node_modules/

install_dependencies: 
  script: 
    - "npm install"
  stage: build
  artifacts: 
    paths: 
      - node_modules/
testing_testing: 
  script: "npm run test-headless"
  stage: test
tags: 
  - test



