stages:
  - test
  - build
cache:
  paths:
  - node_modules/

test-job1:
  stage: test
  image: ubuntu:cwpnode
  tags:
    - cwpunittests
  before_script:
    - sudo npm install
  
  script:
    - echo "This job tests something"
    - sudo npm run test-headless
  only:
    - CWP-CodeBase
build:
  stage: build
  image: ubuntu:cwpnode
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - CWP-CodeBase
