stages:
  - test
  - build
cache:
  paths:
  - node_modules/

test-job1:
  stage: test
  image: ubuntu:cwpnode
  tags:
    - cwpunittests
  before_script:
    - sudo npm install
  
  script:
    - echo "This job tests something"
    - sudo npm run test-headless
  only:
    - CWP-CodeBase
