version: 0
os: linux
files:
  - source: /dist/
    destination: /usr/share/nginx/html
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 30
      runas: root
    - location: scripts/stop_server
      timeout: 60
      runas: root
    - location: scripts/start_server
      timeout: 60
      runas: root
  
#### End of file ####
