# 1. Set APP_ENV environment variable by running the following command in your commnand window (see the notes below if on Windows).

#    export APP_ENV=development or export APP_ENV=production
#    export DEPLOYMENT_ENV=development or DEPLOYMENT_ENV=testing or DEPLOYMENT_ENV=staging or DEPLOYMENT_ENV=production

#    NOTE: If you're on Windows use one of the following commands to create the environment variables.

#    For the standard Windows DOS command shell use `set` instead of `export` for environment variables.
#    For Windows Powershell use `$env:APP_ENV = "value"`.

#    $env:APP_ENV="development" or $env:APP_ENV="production"
#    $env:DEPLOYMENT_ENV="development"

# 2. Run docker compose build
# 3. Run docker compose up -d

version: '3.8'
services:
  nginx:
    container_name: nginx-service-${DEPLOYMENT_ENV}
    image: nginx-service-${DEPLOYMENT_ENV}
    build:
      context: .
      dockerfile: .docker/nginx.${DEPLOYMENT_ENV}.dockerfile
      args:
        - NPM_AUTH_TOKEN=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
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - wi
      - wi-abap
      - mcc-spcc-abap
      - dashboard
      - data-collector
    networks:
      - app-network

  wi:
    container_name: wi-service-${DEPLOYMENT_ENV}
    image: wi-service-${DEPLOYMENT_ENV}
    build:
      context: ${BACKEND_HOME}/WorkInstructions
      dockerfile: .docker/wi-service.deployment.dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/wi-service/.docker/google-cloud-authentication/CWP-S2T_5d8404bd7ee9e7145a60f2778956aef6b96b822f.json
      - NODE_ENV=${APP_ENV}
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV}
      - MONGODB_HOST_NAME=10.0.0.27
    ports:
      - '8001:8001'
    networks:
      - app-network

  wi-abap:
    container_name: wi-abap-service-${DEPLOYMENT_ENV}
    image: wi-abap-service-${DEPLOYMENT_ENV}
    build:
      context: ${BACKEND_HOME}/WorkInstructions
      dockerfile: .docker/wi-abap-service.deployment.dockerfile
    environment:
      - NODE_ENV=${APP_ENV}
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV}
    ports:
      - '8002:8002'
    networks:
      - app-network

  mcc-spcc-abap:
    container_name: mcc-spcc-abap-service-${DEPLOYMENT_ENV}
    image: mcc-spcc-abap-service-${DEPLOYMENT_ENV}
    build:
      context: ${BACKEND_HOME}/MCC_SCC
      dockerfile: .docker/mcc-spcc-abap-service.deployment.dockerfile
    environment:
      - NODE_ENV=${APP_ENV}
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV}
      - MONGODB_HOST_NAME=10.0.0.27
      - REDIS_HOST_NAME=cwppoc.bfq93e.clustercfg.use1.cache.amazonaws.com
    ports:
      - '8003:8003'
    networks:
      - app-network

  dashboard:
    container_name: dashboard-service-${DEPLOYMENT_ENV}
    image: dashboard-service-${DEPLOYMENT_ENV}
    build:
      context: ${BACKEND_HOME}/Reports
      dockerfile: .docker/dashboard-service.deployment.dockerfile
    environment:
      - NODE_ENV=${APP_ENV}
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV}
      - MONGODB_HOST_NAME=10.0.0.27
    ports:
      - '8004:8004'
    networks:
      - app-network

  data-collector:
    container_name: data-collector-service-${DEPLOYMENT_ENV}
    image: data-collector-service-${DEPLOYMENT_ENV}
    build:
      context: ${BACKEND_HOME}/DataCollectorService
      dockerfile: .docker/data-collector-service.deployment.dockerfile
    environment:
      - NODE_ENV=${APP_ENV}
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV}
      - MONGODB_HOST_NAME=10.0.0.27
      - NODE_CONFIG_ENV=${DEPLOYMENT_ENV}
    ports:
      - '8005:8005'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
