# 1. Update `BACKEND_HOME` environment variable(backend source code home path) in .docker/env/[development|testing|staging|production].env file from CWP HOME
# 2. Set NPM_AUTH_TOKEN, MYSQL_PASSWORD, MYSQL_ROOT_PASSWORD & ENCRYPTION_KEY environment varibles in your commnand window.

# In Windows
# 3. Run `docker compose --env-file .\.docker\env\[development|testing|staging|production].env build`
# 4. Run `docker compose --env-file .\.docker\env\[development|testing|staging|production].env up`

# In Linux
# 3. Run `docker compose --env-file .docker/env/[development|testing|staging|production].env build`
# 4. Run `docker compose --env-file .docker/env/[development|testing|staging|production].env up`

################ OR ################

# 1. Set BACKEND_HOME, APP_ENV, DEPLOYMENT_ENV,MYSQL_HOST_NAME, MYSQL_PORT, MYSQL_USER_NAME, MYSQL_DATABASE, REDIS_HOST_NAME, REDIS_PORT, REDIS_TTL, NPM_AUTH_TOKEN, MYSQL_PASSWORD, MYSQL_ROOT_PASSWORD & ENCRYPTION_KEY environment variable by running the following command in your commnand window (see the notes below if on Windows).

#    export BACKEND_HOME='backend home path comes here...'
#    export APP_ENV=development or export APP_ENV=production
#    export DEPLOYMENT_ENV=development or DEPLOYMENT_ENV=testing or DEPLOYMENT_ENV=staging or DEPLOYMENT_ENV=production
#    export MYSQL_HOST_NAME='MySQL hostname comes here...'
#    export MYSQL_PORT='MySQL port comes here...'
#    export MYSQL_USER_NAME='MySQL database username comes here...'
#    export MYSQL_DATABASE='MySQL database for catalog DB comes here...'
#    export REDIS_HOST_NAME='Redis hostname comes here...'
#    export REDIS_PORT='Redis port comes here...'
#    export REDIS_TTL='Redis TTL for tenants data comes here...'
#    export NPM_AUTH_TOKEN='npm authentication token comes here...'
#    export MYSQL_PASSWORD='MySQL password for database comes here...'
#    export MYSQL_ROOT_PASSWORD='MySQL root password for databases comes here...'
#    export ENCRYPTION_KEY='Encryption key comes here...'

#    NOTE: If you're on Windows use one of the following commands to create the environment variables.

#    For the standard Windows DOS command shell use `set` instead of `export` for environment variables.
#    For Windows Powershell use `$env:APP_ENV = "value"`.

#    $env:BACKEND_HOME="backend home path comes here..."
#    $env:APP_ENV="development" or $env:APP_ENV="production"
#    $env:DEPLOYMENT_ENV="development"
#    $env:MYSQL_HOST_NAME='MySQL hostname comes here...'
#    $env:MYSQL_PORT='MySQL port comes here...'
#    $env:MYSQL_USER_NAME='MySQL database username comes here...'
#    $env:MYSQL_DATABASE='MySQL database for catalog DB comes here...'
#    $env:REDIS_HOST_NAME='Redis hostname comes here...'
#    $env:REDIS_PORT='Redis port comes here...'
#    $env:REDIS_TTL='Redis TTL for tenants data comes here...'
#    $env:NPM_AUTH_TOKEN="npm authentication token comes here..."
#    $env:MYSQL_PASSWORD='MySQL password for database comes here...'
#    $env:MYSQL_ROOT_PASSWORD='MySQL root password for databases comes here...'
#    $env:ENCRYPTION_KEY='Encryption key comes here...'

# 2. Run docker compose -f docker-compose.deployment.yml build
# 3. Run docker compose -f docker-compose.deployment.yml up -d

version: '3.8'
services:
  nginx:
    container_name: nginx-${DEPLOYMENT_ENV}
    image: nginx-${DEPLOYMENT_ENV}
    build:
      context: .
      dockerfile: .docker/nginx.${DEPLOYMENT_ENV}.dockerfile
      args:
        - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
        - ENCRYPTION_KEY=${ENCRYPTION_KEY}
        - TENANTS_COUNT=${TENANTS_COUNT}
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - wi
      - wi-abap
      - mcc-spcc-abap
      - dashboard
      - data-collector
    networks:
      - app-network

  wi:
    container_name: wi-${DEPLOYMENT_ENV}
    image: wi-${DEPLOYMENT_ENV}
    build:
      context: ${BACKEND_HOME}/WorkInstructions
      dockerfile: .docker/wi.deployment.dockerfile
      args:
        - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
    restart: always
    environment:
      - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/wi/.docker/google-cloud-authentication/CWP-S2T_5d8404bd7ee9e7145a60f2778956aef6b96b822f.json
      - NODE_ENV=${APP_ENV}
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV}
      - MYSQL_HOST_NAME=mysql-${DEPLOYMENT_ENV}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER_NAME=${MYSQL_USER_NAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST_NAME=${REDIS_HOST_NAME}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_TTL=${REDIS_TTL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    ports:
      - '8001:8001'
    networks:
      - app-network

  wi-abap:
    container_name: wi-abap-${DEPLOYMENT_ENV}
    image: wi-abap-${DEPLOYMENT_ENV}
    build:
      context: ${BACKEND_HOME}/WorkInstructions
      dockerfile: .docker/wi-abap.deployment.dockerfile
      args:
        - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
    restart: always
    environment:
      - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
      - NODE_ENV=${APP_ENV}
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV}
      - MYSQL_HOST_NAME=mysql-${DEPLOYMENT_ENV}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER_NAME=${MYSQL_USER_NAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST_NAME=${REDIS_HOST_NAME}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_TTL=${REDIS_TTL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    ports:
      - '8002:8002'
    networks:
      - app-network

  mcc-spcc-abap:
    container_name: mcc-spcc-abap-${DEPLOYMENT_ENV}
    image: mcc-spcc-abap-${DEPLOYMENT_ENV}
    build:
      context: ${BACKEND_HOME}/MCC_SCC
      dockerfile: .docker/mcc-spcc-abap.deployment.dockerfile
      args:
        - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
    restart: always
    environment:
      - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
      - NODE_ENV=${APP_ENV}
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV}
      - MYSQL_HOST_NAME=mysql-${DEPLOYMENT_ENV}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER_NAME=${MYSQL_USER_NAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST_NAME=${REDIS_HOST_NAME}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_TTL=${REDIS_TTL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    ports:
      - '8003:8003'
    networks:
      - app-network

  dashboard:
    container_name: dashboard-${DEPLOYMENT_ENV}
    image: dashboard-${DEPLOYMENT_ENV}
    build:
      context: ${BACKEND_HOME}/Reports
      dockerfile: .docker/dashboard.deployment.dockerfile
      args:
        - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
    restart: always
    environment:
      - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
      - NODE_ENV=${APP_ENV}
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV}
      - MYSQL_HOST_NAME=mysql-${DEPLOYMENT_ENV}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER_NAME=${MYSQL_USER_NAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST_NAME=${REDIS_HOST_NAME}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_TTL=${REDIS_TTL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    ports:
      - '8004:8004'
    networks:
      - app-network

  data-collector:
    container_name: data-collector-${DEPLOYMENT_ENV}
    image: data-collector-${DEPLOYMENT_ENV}
    build:
      context: ${BACKEND_HOME}/DataCollectorService
      dockerfile: .docker/data-collector.deployment.dockerfile
      args:
        - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
    restart: always
    environment:
      - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
      - NODE_ENV=${APP_ENV}
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV}
    ports:
      - '8005:8005'
    networks:
      - app-network

  logging-service:
    container_name: logging-service-${DEPLOYMENT_ENV}
    image: logging-service-${DEPLOYMENT_ENV}
    build:
      context: ${BACKEND_HOME}/LoggingService
      dockerfile: .docker/logging-service.deployment.dockerfile
      args:
        - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
    restart: always
    environment:
      - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
      - NODE_ENV=${APP_ENV}
    ports:
      - '8006:8006'
    depends_on:
      - rabbitmq
    networks:
      - app-network

  user-service:
    container_name: user-service-${DEPLOYMENT_ENV}
    image: user-service-${DEPLOYMENT_ENV}
    build:
      context: ${BACKEND_HOME}/UserService
      dockerfile: .docker/user-service.deployment.dockerfile
      args:
        - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
    restart: always
    environment:
      - NODE_ENV=${APP_ENV}
      - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
      - MYSQL_HOST_NAME=mysql-${DEPLOYMENT_ENV}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER_NAME=${MYSQL_USER_NAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST_NAME=${REDIS_HOST_NAME}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_TTL=${REDIS_TTL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
      - SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
      - CLIENT_SIGNING_SECRET=${CLIENT_SIGNING_SECRET}
      - SLACK_STATE_SECRET=${SLACK_STATE_SECRET}
    ports:
      - '8007:8007'
    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq-${DEPLOYMENT_ENV}
    image: rabbitmq:3.9-management-alpine
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq/
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network

volumes:
  rabbitmqdata:

networks:
  app-network:
    driver: bridge
