export const importedWorkInstructions = {
  WorkInstruction_Sample_1: [
    {
      WorkInstruction: "Sample WorkInstruction1",
      AssignedObjects:
        "ORDER TYPE: Test Order, ORDER NUMBER: {value}, EQUIPMENT NUMBER: 12345, KEY FOR TASK LIST GROUP: {value}, TASK LIST TYPE: {value}, NOTIFICATION TYPE: {value}, NOTIFICATION NO: {value}",
      Category: "Sample Category1",
      SafetyKit: "Sample Kit1, Sample Kit2 ",
      SpareParts: "Sample Spare Part1, Sample Spare Part2",
      Tools: "Sample Tool1, Sample Tool2",
      Cover_Image_Name: "doc-placeholder.png",
      Cover_Image: "",
      StepTitle: "",
      Instruction: "",
      Warning: "",
      ReactionPlan: "",
      Hint: "",
      Attachment_1_Name: "",
      Attachment_1: "",
      Attachment_2_Name: "",
      Attachment_2: "",
    },
    {
      WorkInstruction: "",
      AssignedObjects: "",
      Category: "",
      SafetyKit: "",
      SpareParts: "",
      Tools: "",
      Cover_Image: "",
      StepTitle: "Sample Title1",
      Instruction: "1. Sample Instruction1 2. Sample Instruction2",
      Warning: "● Sample Warning1 ● Sample Warning2",
      ReactionPlan: "Sample ReactionPlan",
      Hint: "Sample Hint",
      Attachment_1_Name: "SampleImgWIMVP.jpg",
      Attachment_1: "U2FtcGxlSW1nV0lNVlAuanBn",
      Attachment_2_Name: "SampleImgWIMVP.jpg",
      Attachment_2: "U2FtcGxlSW1nV0lNVlAuanBn",
    },
    {
      WorkInstruction: "",
      AssignedObjects: "",
      Category: "",
      SafetyKit: "",
      SpareParts: "",
      Tools: "",
      Cover_Image: "",
      StepTitle: "Sample Title2",
      Instruction: "1. Sample Instruction1 2. Sample Instruction2",
      Warning: "1. Sample Warning1 2. Sample Warning2",
      ReactionPlan: "Sample ReactionPlan",
      Hint: "Sample Hint",
      Attachment_1_Name: "",
      Attachment_1: "",
      Attachment_2_Name: "",
      Attachment_2: "",
    },
    {
      WorkInstruction: "",
      AssignedObjects: "",
      Category: "",
      SafetyKit: "",
      SpareParts: "",
      Tools: "",
      Cover_Image: "",
      StepTitle: "Sample Title3",
      Instruction: "1. Sample Instruction1 2. Sample Instruction2",
      Warning: "● Sample Warning1 ● Sample Warning2",
      ReactionPlan: "Sample ReactionPlan",
      Hint: "Sample Hint",
      Attachment_1_Name: "SampleImgWIMVP.jpg",
      Attachment_1: "",
      Attachment_2_Name: "SampleImgWIMVP.jpg",
      Attachment_2: "",
    },
  ],
  WorkInstruction_Sample_2: [
    {
      WorkInstruction: "Sample WorkInstruction2",
      AssignedObjects:
        "ORDER TYPE: {value}, ORDER NUMBER: {value}, EQUIPMENT NUMBER: {value}, KEY FOR TASK LIST GROUP: {value}, TASK LIST TYPE: {value}, NOTIFICATION TYPE: {value}, NOTIFICATION NO: {value}",
      Category: "Sample Category2",
      SafetyKit: "Sample Kit1, Sample Kit2 ",
      SpareParts: "Sample Spare Part1, Sample Spare Part2",
      Tools: "Sample Tool1, Sample Tool2",
      Cover_Image_Name: "doc-placeholder.png",
      Cover_Image: "",
      StepTitle: "",
      Instruction: "",
      Warning: "",
      ReactionPlan: "",
      Hint: "",
      Attachment_1_Name: "",
      Attachment_1: "",
      Attachment_2_Name: "",
      Attachment_2: "",
    },
    {
      WorkInstruction: "",
      AssignedObjects: "",
      Category: "",
      SafetyKit: "",
      SpareParts: "",
      Tools: "",
      Cover_Image: "",
      StepTitle: "Sample Title1",
      Instruction: "1. Sample Instruction1 2. Sample Instruction2",
      Warning: "● Sample Warning1 ● Sample Warning2",
      ReactionPlan: "Sample ReactionPlan",
      Hint: "Sample Hint",
      Attachment_1_Name: "SampleImgWIMVP.jpg",
      Attachment_1: "U2FtcGxlSW1nV0lNVlAuanBn",
      Attachment_2_Name: "SampleImgWIMVP.jpg",
      Attachment_2: "U2FtcGxlSW1nV0lNVlAuanBn",
    },
    {
      WorkInstruction: "",
      AssignedObjects: "",
      Category: "",
      SafetyKit: "",
      SpareParts: "",
      Tools: "",
      Cover_Image: "",
      StepTitle: "Sample Title2",
      Instruction: "1. Sample Instruction1 2. Sample Instruction2",
      Warning: "1. Sample Warning1 2. Sample Warning2",
      ReactionPlan: "Sample ReactionPlan",
      Hint: "Sample Hint",
      Attachment_1_Name: "SampleImgWIMVP.jpg",
      Attachment_1: "",
      Attachment_2_Name: "SampleImgWIMVP.jpg",
      Attachment_2: "",
    },
    {
      WorkInstruction: "",
      AssignedObjects: "",
      Category: "",
      SafetyKit: "",
      SpareParts: "",
      Tools: "",
      Cover_Image: "",
      StepTitle: "Sample Title3",
      Instruction: "1. Sample Instruction1 2. Sample Instruction2",
      Warning: "● Sample Warning1 ● Sample Warning2",
      ReactionPlan: "Sample ReactionPlan",
      Hint: "Sample Hint",
      Attachment_1_Name: "SampleImgWIMVP.jpg",
      Attachment_1: "",
      Attachment_2_Name: "SampleImgWIMVP.jpg",
      Attachment_2: "",
    },
  ],
  WorkInstruction_Sample_3: [
    {
      WorkInstruction: "Sample WorkInstruction3",
      AssignedObjects: "",
      Category: "Sample Category3",
      SafetyKit: "Sample Kit1, Sample Kit2 ",
      SpareParts: "Sample Spare Part1, Sample Spare Part2",
      Tools: "Sample Tool1, Sample Tool2",
      Cover_Image_Name: "doc-placeholder.png",
      Cover_Image: "",
      StepTitle: "",
      Instruction: "",
      Warning: "",
      ReactionPlan: "",
      Hint: "",
      Attachment_1_Name: "",
      Attachment_1: "",
      Attachment_2_Name: "",
      Attachment_2: "",
    }
  ]
};
