export const businessObjects = [
  {
    OBJECTCATEGORY: "WORKORDER",
    FILEDNAME: "AUART",
    FIELDDESCRIPTION: "ORDER TYPE",
    Value: "",
  },
  {
    OBJECTCATEGORY: "WORKORDER",
    FILEDNAME: "AUFNR",
    FIELDDESCRIPTION: "ORDER NUMBER",
    Value: "",
  },
  {
    OBJECTCATEGORY: "WORKORDER",
    FILEDNAME: "EQUNR",
    FIELDDESCRIPTION: "EQUIPMENT NUMBER",
    Value: "",
  },
  {
    OBJECTCATEGORY: "WORKORDER",
    FILEDNAME: "PLNNR",
    FIELDDESCRIPTION: "KEY FOR TASK LIST GROUP",
    Value: "",
  },
  {
    OBJECTCATEGORY: "WORKORDER",
    FILEDNAME: "PLNTY",
    FIELDDESCRIPTION: "TASK LIST TYPE",
    Value: "",
  },
  {
    OBJECTCATEGORY: "NOTIFICATION",
    FILEDNAME: "QMART",
    FIELDDESCRIPTION: "NOTIFICATION TYPE",
    Value: "",
  },
  {
    OBJECTCATEGORY: "NOTIFICATION",
    FILEDNAME: "QMNUM",
    FIELDDESCRIPTION: "NOTIFICATION NO",
    Value: "",
  },
];
