import { of } from "rxjs"

export const rawTechniciansSPCC$ = of([
    {
        "UserID": "C5010053",
        "OrderNumber": "",
        "UserName": "C5010053",
        "FirstName": "C5010053",
        "LastName": ""
    },
    {
        "UserID": "E5000164",
        "OrderNumber": "",
        "UserName": "kanna",
        "FirstName": "santhosh chakrawarthy kanna",
        "LastName": ""
    },
    {
        "UserID": "E5000317",
        "OrderNumber": "",
        "UserName": "Gedela",
        "FirstName": "Sridhar Gedela",
        "LastName": ""
    },
    {
        "UserID": "E5000550",
        "OrderNumber": "",
        "UserName": "Patil",
        "FirstName": "Shrinivas Patil",
        "LastName": ""
    },
    {
        "UserID": "E5000552",
        "OrderNumber": "",
        "UserName": "Gunda",
        "FirstName": "Vinay Kumar Gunda",
        "LastName": ""
    }
])

export const expectedTechniciansSPCC = [{
    "userId": "C5010053",
    "userName": "C5010053",
    "fName": "C5010053",
    "LName": ""
},
{
    "userId": "E5000164",
    "userName": "kanna",
    "fName": "santhosh chakrawarthy kanna",
    "LName": ""
},
{
    "userId": "E5000317",
    "userName": "Gedela",
    "fName": "Sridhar Gedela",
    "LName": ""
},
{
    "userId": "E5000550",
    "userName": "Patil",
    "fName": "Shrinivas Patil",
    "LName": ""
},
{
    "userId": "E5000552",
    "userName": "Gunda",
    "fName": "Vinay Kumar Gunda",
    "LName": ""
}
]

export const rawWorkOrdersSPCC = of([
    {
        "AUFNR": "836737",
        "USNAM": "E5000164",
        "ERDAT": "/Date(1638403200000)/",
        "PRIOKX": "Very High",
        "AAUFNR": "",
        "STAGED": 0,
        "STATUSKEY": "2",
        "TOTITEMS": 0,
        "PRIOK": "1",
        "PUPTIME": "",
        "STATUSTXT": "Assigned For Picking",
        "WERKS": "1000",
        "ASSIGNEE": "santhosh chakrawarthy kanna",
        "ERNAM": "E5000260",
        "GSTRP": "/Date(1638403200000)/",
        "GLTRP": "/Date(1638835200000)/",
        "STOCK": 0,
        "NONSTOCK": 0,
        "PARTS_AVAIL": "",
        "WAITING_PARTS": "X",
        "EXTENSION": "",
        "TRANSACTIONID": ""
    },
    {
        "AUFNR": "836738",
        "USNAM": "C5010053",
        "ERDAT": "/Date(1638403200000)/",
        "PRIOKX": "High",
        "AAUFNR": "",
        "STAGED": 0,
        "STATUSKEY": "2",
        "TOTITEMS": 0,
        "PRIOK": "2",
        "PUPTIME": "",
        "STATUSTXT": "Assigned For Picking",
        "WERKS": "1000",
        "ASSIGNEE": "C5010053",
        "ERNAM": "E5000260",
        "GSTRP": "/Date(1638403200000)/",
        "GLTRP": "/Date(1638403200000)/",
        "STOCK": 0,
        "NONSTOCK": 0,
        "PARTS_AVAIL": "",
        "WAITING_PARTS": "X",
        "EXTENSION": "",
        "TRANSACTIONID": ""
    },
    {
        "AUFNR": "836739",
        "USNAM": "E5000550",
        "ERDAT": "/Date(1638403200000)/",
        "PRIOKX": "Medium",
        "AAUFNR": "",
        "STAGED": 0,
        "STATUSKEY": "3",
        "TOTITEMS": 2,
        "PRIOK": "3",
        "PUPTIME": "",
        "STATUSTXT": "Assigned For Picking",
        "WERKS": "1000",
        "ASSIGNEE": "Shrinivas Patil",
        "ERNAM": "E5000260",
        "GSTRP": "/Date(1638403200000)/",
        "GLTRP": "/Date(1638489600000)/",
        "STOCK": 2,
        "NONSTOCK": 0,
        "PARTS_AVAIL": "X",
        "WAITING_PARTS": "",
        "EXTENSION": "",
        "TRANSACTIONID": ""
    },
    {
        "AUFNR": "836780",
        "USNAM": "",
        "ERDAT": "/Date(1638748800000)/",
        "PRIOKX": "",
        "AAUFNR": "",
        "STAGED": 0,
        "STATUSKEY": "1",
        "TOTITEMS": 0,
        "PRIOK": "",
        "PUPTIME": "",
        "STATUSTXT": "Kits Required",
        "WERKS": "1000",
        "ASSIGNEE": "",
        "ERNAM": "E5000507",
        "GSTRP": "/Date(1638835200000)/",
        "GLTRP": "/Date(1639612800000)/",
        "STOCK": 0,
        "NONSTOCK": 0,
        "PARTS_AVAIL": "X",
        "WAITING_PARTS": "",
        "EXTENSION": "",
        "TRANSACTIONID": ""
    },
    {
        "AUFNR": "836781",
        "USNAM": "",
        "ERDAT": "/Date(1638835200000)/",
        "PRIOKX": "",
        "AAUFNR": "",
        "STAGED": 0,
        "STATUSKEY": "4",
        "TOTITEMS": 0,
        "PRIOK": "",
        "PUPTIME": "",
        "STATUSTXT": "Kits Required",
        "WERKS": "1000",
        "ASSIGNEE": "",
        "ERNAM": "E5000507",
        "GSTRP": "/Date(1638835200000)/",
        "GLTRP": "/Date(1639612800000)/",
        "STOCK": 0,
        "NONSTOCK": 0,
        "PARTS_AVAIL": "X",
        "WAITING_PARTS": "",
        "EXTENSION": "",
        "TRANSACTIONID": ""
    },
    {
        "AUFNR": "836815",
        "USNAM": "",
        "ERDAT": "/Date(1640304000000)/",
        "PRIOKX": "High",
        "AAUFNR": "",
        "STAGED": 0,
        "STATUSKEY": "5",
        "TOTITEMS": 0,
        "PRIOK": "2",
        "PUPTIME": "",
        "STATUSTXT": "Kits Required",
        "WERKS": "1000",
        "ASSIGNEE": "",
        "ERNAM": "MWORKORDER1",
        "GSTRP": "/Date(1640304000000)/",
        "GLTRP": "/Date(1640304000000)/",
        "STOCK": 0,
        "NONSTOCK": 0,
        "PARTS_AVAIL": "X",
        "WAITING_PARTS": "",
        "EXTENSION": "",
        "TRANSACTIONID": ""
    }])

export const expectedWorkOrdersSPCC = {
    "1": [
        {
            "statusCode": "1",
            "status": "Kits Required",
            "personDetails": "",
            "priorityNumber": "",
            "priorityStatus": "",
            "colour": "",
            "workOrderID": "836780",
            "workOrderDesc": "",
            "equipmentID": "",
            "equipmentName": "",
            "dueDate": "2021-12-07T00:00:00.000Z",
            "estimatedTime": "",
            "actualTime": "",
            "partsavailable": "PARTS AVAILABLE",
            "progressValue": null,
            "staged": 0,
            "totItems": 0,
            "assigneeId": "",
            "assignee": ""
        }
    ],
    "2": [
        {
            "statusCode": "2",
            "status": "Assigned for Picking",
            "personDetails": "",
            "priorityNumber": "1",
            "priorityStatus": "Very High Priority",
            "colour": "",
            "workOrderID": "836737",
            "workOrderDesc": "",
            "equipmentID": "",
            "equipmentName": "",
            "dueDate": "2021-12-02T00:00:00.000Z",
            "estimatedTime": "",
            "actualTime": "",
            "partsavailable": "WAITING ON PARTS",
            "progressValue": null,
            "staged": 0,
            "totItems": 0,
            "assigneeId": "E5000164",
            "assignee": "santhosh chakrawarthy kanna"
        },
        {
            "statusCode": "2",
            "status": "Assigned for Picking",
            "personDetails": "",
            "priorityNumber": "2",
            "priorityStatus": "High Priority",
            "colour": "",
            "workOrderID": "836738",
            "workOrderDesc": "",
            "equipmentID": "",
            "equipmentName": "",
            "dueDate": "2021-12-02T00:00:00.000Z",
            "estimatedTime": "",
            "actualTime": "",
            "partsavailable": "WAITING ON PARTS",
            "progressValue": null,
            "staged": 0,
            "totItems": 0,
            "assigneeId": "C5010053",
            "assignee": "C5010053"
        }
    ],
    "3": [
        {
            "statusCode": "3",
            "status": "Kitting in Progress",
            "personDetails": "",
            "priorityNumber": "3",
            "priorityStatus": "Medium Priority",
            "colour": "",
            "workOrderID": "836739",
            "workOrderDesc": "",
            "equipmentID": "",
            "equipmentName": "",
            "dueDate": "2021-12-02T00:00:00.000Z",
            "estimatedTime": "",
            "actualTime": "",
            "partsavailable": "PARTS AVAILABLE",
            "progressValue": 0,
            "staged": 0,
            "totItems": 2,
            "assigneeId": "E5000550",
            "assignee": "Shrinivas Patil"
        }
    ],
    "4": [
        {
            "statusCode": "4",
            "status": "Kits Complete",
            "personDetails": "",
            "priorityNumber": "",
            "priorityStatus": "",
            "colour": "",
            "workOrderID": "836781",
            "workOrderDesc": "",
            "equipmentID": "",
            "equipmentName": "",
            "dueDate": "2021-12-07T00:00:00.000Z",
            "estimatedTime": "",
            "actualTime": "",
            "partsavailable": "PARTS AVAILABLE",
            "progressValue": null,
            "staged": 0,
            "totItems": 0,
            "assigneeId": "",
            "assignee": ""
        }
    ],
    "5": [
        {
            "statusCode": "5",
            "status": "Kits Issued",
            "personDetails": "",
            "priorityNumber": "2",
            "priorityStatus": "High Priority",
            "colour": "",
            "workOrderID": "836815",
            "workOrderDesc": "",
            "equipmentID": "",
            "equipmentName": "",
            "dueDate": "2021-12-24T00:00:00.000Z",
            "estimatedTime": "",
            "actualTime": "",
            "partsavailable": "PARTS AVAILABLE",
            "progressValue": null,
            "staged": 0,
            "totItems": 0,
            "assigneeId": "",
            "assignee": ""
        }
    ]
}